---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/gberenice/tf-controller-helloworld
  ref:
    branch: backend_s3
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  workspace: dev
  approvePlan: auto
  interval: 1m
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket                      = "tf-controller-tfstate"
        acl                         = "bucket-owner-full-control"
        key                         = "terraform.tfstate"
        workspace_key_prefix        = "helloworld-tf"
        region                      = "us-east-1"
        dynamodb_table              = "tf-controller-tfstate-backend-lock"
        encrypt                     = true
      }
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  writeOutputsToSecret:
    name: helloworld-outputs
  destroyResourcesOnDeletion: true
  # `aws-credentials` should be created manually. In real setup this should be configured with IRSA.
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-credentials
